### ISSUE TITLE
Getting error when generating Qr Code - Urgent as we need the codes now!

### ISSUE THREAD

**Issue by fomar-dev** [innova-apps/QR-Code-Generator-Add-On-for-Google-Spreadsheets#15] opened 2020-09-17 23:23 UTC
We have an issue when generating Qr-Codes. 

When we generate one single row or multiple rows to generate the code the document is created. However, when we open the document we receive an error. See and open the attached document.

https://docs.google.com/document/d/1OtHe6omRHgNpuKB9H54q3yaGvxNHrODol8bvSz-b-O4/edit?usp=sharing

**Comment by ghost** [comment] 2020-09-19 07:48
Hi, i also facing this problem. Since i did some communication with Google Docs product team, this is caused by the Innova App team did not update their QR Code Generator add-on and cause a conflict. So, please do some update.

**Comment by innova-apps** [comment] 2020-09-21 09:54
We can reproduce the issue and we are looking into it right now as many users are reporting the issue. Something must have changed on Google's side as there has not been any add-on updates recently.

**Comment by innova-apps** [comment] 2020-09-21 10:33
We narrowed down the issue. It happens when the first cell in a template is being copied to the output document. No error is thrown, but the document cannot be opened. We will have to open an issue with Google Dev team to investigate.

Good news is that **there is a workaround**! Just click on the doc in Google Drive and Download it. It will convert it to Microsoft Word and that document contains QR codes & images.

Use this workaround until that issue is resolved. Sorry for the inconvenience!

**Comment by innova-apps** [comment] 2020-09-21 12:47
Issue opened with Google DEV team:
[https://issuetracker.google.com/issues/169006039](https://issuetracker.google.com/issues/169006039)

**Comment by innova-apps** [comment] 2020-09-23 16:05
Issue has been fixed in version 4.3.

**Closed as completed by innova-apps** 2020-09-23 16:05 UTC
Labels: bug
